package ro.tatacalu.github.bot.domain;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Value;
import org.hibernate.validator.constraints.NotEmpty;

import javax.validation.constraints.NotNull;
import java.net.URI;
import java.time.Instant;

/**
 * Domain model class representing a GitHub Issue Comment.
 *
 * Getters, setters, equals(), hashCode() and toString() are generated by Lombok.
 */
@Value
public class IssueComment {

    @NotNull
    Long id;

    @NotNull
    URI url;

    @NotNull
    @JsonProperty("issue_url")
    URI issueUrl;

    @NotNull
    @NotEmpty
    String body;

    @NotNull
    @JsonProperty("created_at")
    Instant createdAt;

    @NotNull
    @JsonProperty("updated_at")
    Instant updatedAt;
}
